### PR TITLE
Spline offset data

### PR DESCRIPTION
**Pull request by Frickerson**
This change is [Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10)

### CODE REVIEW

**Review by MaxDaniels — APPROVED** [review]

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10)* status: all files reviewed, 4 unresolved discussions (waiting on @Fr0oZzFred and @VectorGamez)

___
*[`Source/SplineFollow/Private/Components/SFSplineFollowingMovementComponent.cpp` line 34 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVKDNFDLos7CAfX7Js:-NyVKDNFDLos7CAfX7Jt:btcw7pc) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Private/Components/SFSplineFollowingMovementComponent.cpp#L34)):*
> ```cpp
>     check( offset_data != nullptr );
> 
>     OffsetData = offset_data;
> ```

initialize in the ctor init list

```
FSFSplineOffsetInfo::FSFSplineOffsetInfo( USFSplineOffsetData * offset_data ) :
    OffsetCurve( offset_data->OffsetCurve )
{
    check( offset_data != nullptr );

```
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 2 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJnoXCGCcLmPywf77:-NyVJnoXCGCcLmPywf78:b-rxlbwa) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L2)):*
> ```objc
> #pragma once
> #include "Curves/CurveVector.h"
> ```

<> and empty line above
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 15 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJqp03vJ7FKtBp6R_:-NyVJqp03vJ7FKtBp6Ra:b1rwtwv) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L15)):*
> ```objc
> DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam( FSFOnSplineOffsetFinishedDelegate, USFSplineOffsetData *, offset_data );
> 
> struct FSFSplineOffsetInfo
> ```

move inside the class
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 23 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJvGu-9MII9N4tI3-:-NyVJvGu-9MII9N4tI30:b-2ty3vt) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L23)):*
> ```objc
>     bool ApplyOffsetToTransform( FTransform & transform, float delta_time );
> 
>     TObjectPtr< USFSplineOffsetData > OffsetData;
> ```

no. copy the members here too and initialize them in the ctor.
if you use a pointer, you don't benefit from the packed memory of the array as the CPU will need to do ping pong between the struct and the data asset

**Review by Frickerson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Fr0oZzFred and @TheEmidee)

___
*[`Source/SplineFollow/Private/Components/SFSplineFollowingMovementComponent.cpp` line 34 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVKDNFDLos7CAfX7Js:-NyVPjRgBpmXqX-UTvB7:b-896fix) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Private/Components/SFSplineFollowingMovementComponent.cpp#L34)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

initialize in the ctor init list

```
FSFSplineOffsetInfo::FSFSplineOffsetInfo( USFSplineOffsetData * offset_data ) :
    OffsetCurve( offset_data->OffsetCurve )
{
    check( offset_data != nullptr );

```
</blockquote></details>

Done.
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 2 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJnoXCGCcLmPywf77:-NyVPo-B2l6Uxt7lcDRf:b-896fix) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L2)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

<> and empty line above
</blockquote></details>

Done.
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 15 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJqp03vJ7FKtBp6R_:-NyVPsst09CoX0VGV1qj:b-896fix) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L15)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

move inside the class
</blockquote></details>

Done.
___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 23 at r2](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVJvGu-9MII9N4tI3-:-NyVTBl_0eSylhzbbnS8:bgpxg56) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/ac84163294af2a7f721805d250ee2cd876e06c7d/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L23)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

no. copy the members here too and initialize them in the ctor.
if you use a pointer, you don't benefit from the packed memory of the array as the CPU will need to do ping pong between the struct and the data asset
</blockquote></details>

Discussed

**Review by TheEmidee — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred and @VectorGamez)

___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 196 at r3](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVZWZr7f2Dj99Stg89:-NyVZWZr7f2Dj99Stg8A:b-ra7tym) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/255d1f1db6bb7a6aef15d5f6367c605b1b73635b/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L196)):*
> ```objc
>         FRuntimeVectorCurve OffsetCurve;
>         ESFSplineOffsetType OffsetType;
>         uint8 bResetOnEnd : 1;
> ```

use a bool (uint8 bXXX : 1 are for UPROPERTIES)

**Review by Frickerson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Fr0oZzFred and @TheEmidee)

___
*[`Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h` line 196 at r3](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-NyVZWZr7f2Dj99Stg89:-NyVe7GF9j5jUlgJnwdd:b-896fix) ([raw file](https://github.com/TheEmidee/UESplineFollow/blob/255d1f1db6bb7a6aef15d5f6367c605b1b73635b/Source/SplineFollow/Public/Components/SFSplineFollowingMovementComponent.h#L196)):*
<details><summary><i>Previously, TheEmidee (Michael Delva) wrote…</i></summary><blockquote>

use a bool (uint8 bXXX : 1 are for UPROPERTIES)
</blockquote></details>

Done.

**Review by TheEmidee — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TheEmidee/UESplineFollow/10#-:-NyWdD8O71dD5doqctF-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fr0oZzFred)

**Pull request merged**
